[nfs]
172.31.90.140 ansible_ssh_user='ec2-user'

[webservers]
172.31.83.14 ansible_ssh_user='ec2-user'
172.31.85.223 ansible_ssh_user='ec2-user'

[db]
172.31.95.163 ansible_ssh_user='ec2-user' 

[lb]
172.31.16.66 ansible_ssh_user='ubuntu'